### ISSUE TITLE
Working directory assumed to be VFS Explorer directory

### ISSUE THREAD

**Issue by rathologic** [isatsam/vfs_toolkit#2]
Attempting to launch the VFS Explorer application through a symlink created with "ln", or from Windows Search, results in a fatal error as program files are sought relative to the execution directory, rather than the location of the application.

![73dacc39bbce9e8c672e178f6415adac](https://github.com/user-attachments/assets/6fbcb571-6bc9-412d-89c3-e95592d0f617)

Steps to reproduce (Windows Git Bash, replace .exe extensions for other OS):
`ln 'vfs_explorer/VFS Explorer.exe' shortcut`, from a directory other than "vfs_explorer"
`./shortcut.exe`

**Comment by isatsam** [comment]
Fixed in #b931020. You should be able to download the latest builds here: [Windows](https://github.com/isatsam/vfs_explorer/actions/runs/10891857072), [Linux](https://github.com/isatsam/vfs_explorer/actions/runs/10891857078)
