### ISSUE TITLE
Add issues/discussion tabs to Photoshop repo

### ISSUE THREAD

**Issue by Gusfit1** [isatsam/vfs_toolkit#3]
I was going to make a pull request, but it wouldn't let me because the original repo is closed.

* [photoshop.svg](https://github.com/albakhtari/photoshop-22-linux/blob/main/images/photoshop.svg) is missing from /images
* I see 'winecfg -v win10' during install but Wine still defaults to Win 7
* Seems to work well with Photoshop 2024 25.0.7.504. Could clean up script to work with other versions as well? Replace all mentions of year then all a user has to do is edit their installation folder names to Adobe Photoshop and it will work.
* Wine/Adobe processes sometimes get caught in limbo after closing. Might be something to do with this specific version though.

![Screenshot From 2024-11-08 22-40-08](https://github.com/user-attachments/assets/a67c28e8-2ea2-43ae-b883-4ea63f3f3d74)

**Comment by isatsam** [comment]
Hey there, I enabled issues and discussions in the Photoshop repository. Does it let you submit a PR if you click on "New pull request", then select "isatsam/photoshop-on-linux" as base repo?

The photoshop.svg image likely fell victim to the purge of copyrighted content. I'm not against adding it back, as I don't think that this specific would actually bring Adobe's evil eye upon us. I wonder however if it's possible to just grab the PS icon from the installation itself somehow. From a quick search I couldn't locate the .ico file, so maybe it's stored inside the .exe after all. However with kde plasma for example all installed applications through wine add their icons to ~/.local/share/icons/hicolor, perhaps we could look for that or do whatever they're doing to extract the icon.

Makes sense to make the installer more version-agnostic. Awhile ago I tried to do that in local, but didn't have time to polish it enough to make it public. It seems that PS runs much better nowadays though, so I'm up for giving the script a much needed makeover. I'll definitely take to look into other issues you mentioned within the next few days. 

Feel free to move this conversation over to either an issue or a discussion, whichever you see fit, in the proper repo. Thanks for reaching out, I didn't even realise the PS repository is a bit borked.
